GET https://api.spotify.com/v1/me/player
content-type: application/json
Authorization: Bearer BQAqJHPjLddMh8dKNVUvG83BFQpDV5OUnY8rttoRhQRBhwMufJ5OqKapA4KP6kNthrCUmgT6EGYcKKRkS7EYNC8M3j4h6QHv0rMqfALbWTWn09xtyfeaNg5jqwObUXebETmDmGjeNXPctTxLar-8NV18xw&token_type=Bearer&expires_in=3600&refresh_token=AQAEsYF3QjkjuAv3DV_eteW1vms94x6y8LVMS-K6JobpSGAdqElfiIwpnwKi7BB91BlQUM5DFYx4Y6sr0rJSfFJU9zlgLynBD1FxDFZpHp8q1uY3lGvPZ3Z4futwl8op5lk
Accept: application/json